<a href="https://colab.research.google.com/github/Kishor911/NNDL-Lab/blob/main/P_2(NNDL).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#AIM = Implement a percepton model using google colab for Binary Classification.
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report

iris = load_iris()

X = iris.data;
y = iris.target

df=pd.DataFrame(X, columns=iris.feature_names)
df["Target"] = y
print(df.head())


   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  Target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]


In [4]:
y=(y==0).astype(int)  #Converted to binary Classification

In [5]:
#Splited dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
#Created Perceptron Model
model = Perceptron(max_iter=1000, eta0=0.1, random_state=42)

In [7]:
#Trained the model
model.fit(X_train, y_train)

#Made predictions
y_pred=model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0


In [8]:
#Prediction
print("\nPredicted Values:")
print(y_pred)

print("\nActual Values:")
print(y_test)

#Confusion Matrix
print("\nConfusion Matrix ")
print(confusion_matrix(y_test, y_pred))

#Classification Report
print("\nClassification Report")
print(classification_report(y_test, y_pred))


Predicted Values:
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1]

Actual Values:
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1]

Confusion Matrix 
[[20  0]
 [ 0 10]]

Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

